### ISSUE TITLE
[bug]:  Error: Unable to get Xcode project information ... Unable to read project 'Runner.xcodeproj'. After Running Flutterfire Configure on MACOS

### ISSUE THREAD

**Issue by biondiBagasta** [invertase/flutterfire_cli#292]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

1.0.0

### Firebase Tools version

13.8.0

### Flutter Doctor Output

[✓] Flutter (Channel stable, 3.19.5, on macOS 14.3 23D56 darwin-arm64, locale
    en-ID)
    • Flutter version 3.19.5 on channel stable at /Users/adamulti/devel/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (5 weeks ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/adamulti/Library/Android/sdk
    • Platform android-34-ext8, build-tools 34.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.86.0)
    • VS Code at /Users/adamulti/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.88.0

### Description

When i run `flutterfire configure` command for my IOS project and then running the project i got this error :
`
Launching lib/main.dart on iPhone 15 in debug mode...
Error: Unable to get Xcode project information:
 2024-05-03 10:05:10.061 xcodebuild[36844:232542] Writing error result bundle to /var/folders/7_/cp_zpfgn6xs2th9fnss_s9w00000gn/T/ResultBundle_2024-03-05_10-05-0010.xcresult
xcodebuild: error: Unable to read project 'Runner.xcodeproj'.
	Reason: Project /Users/adamulti/Documents/Kerja/ADAMULTI CLONE PROJECT/MPN IOS/mpn_clone_ios/ios/Runner.xcodeproj cannot be opened because it is missing its project.pbxproj file.
`

### Steps to reproduce

1. Run `sudo flutter configure`.
2. Register your app to your firebase account.
3. When you're done, Run the project again and it will throwing the error just the description above.

### Expected behavior

the `project.pbxproj file.` is shouldn't missing after running the flutterfire configure command.

### Screenshots

Video Screenshot : 
[https://drive.google.com/file/d/1eNTSsuH3hLvRXAigZFhePUfj2rf7Hugr/view](url)

**Comment by russellwheatley** [comment]
You have spaces in your path, please use the latest dev version which addresses that issue:

```
dart pub global activate flutterfire_cli 1.0.1-dev.0 --overwrite
```

This ought to fix your problem, I'll reopen if it does not.

**Comment by Tolulope05** [comment]
Launching lib/main.dart on iPhone 16e in debug mode...
Error: Unable to get Xcode project information:
 2026-03-02 01:22:58.902 xcodebuild[31594:341059] Writing error result bundle to /var/folders/xq/0fhxw6xx2md39h4dl8232hph0000gn/T/ResultBundle_2026-02-03_1-22-0058 AM.xcresult
xcodebuild: error: Could not resolve package dependencies:
  main/Package.swift:79: Fatal error: Failed to load configuration: fileNotFound("Error loading or parsing pubspec.yaml: Error Domain=NSCocoaErrorDomain Code=260 \"The file “pubspec.yaml” couldn’t be opened because there is no such file.\" UserInfo={NSFilePath=/Users/tolulope/Studio%20Project/liveet/ios/Flutter/ephemeral/Packages/.packages/firebase_messaging/../../pubspec.yaml, NSURL=file:///Users/tolulope/Studio%2520Project/liveet/ios/Flutter/ephemeral/Packages/.packages/firebase_messaging/../../pubspec.yaml, NSUnderlyingError=0x100979f80 {Error Domain=NSPOSIXErrorDomain Code=2 \"No such file or directory\"}}")



Exited (1).

I am using latest version of flutterfire_cli

**Comment by Tolulope05** [comment]
@russellwheatley 

tolulope@Tolulopes-MacBook-Air liveet % dart pub global activate flutterfire_cli

Package flutterfire_cli is currently active at version 1.3.1.
Downloading packages... . (1.0s)
The package flutterfire_cli is already activated at newest available version.
To recompile executables, first run `dart pub global deactivate flutterfire_cli`.
Installed executable flutterfire.
Activated flutterfire_cli 1.3.1.
