### ISSUE TITLE
request:  Add option to add `--token` to Firebase CLI when running in a CI environment

### ISSUE THREAD

**Issue by exaby73** [invertase/flutterfire_cli#78]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Command

flutterfire configure --token "$FIREBASE_TOKEN"

### Description

As a developer, I want to use FlutterFire CLI on a CI environment, namely Codemagic. Since I can't authenticate with Firebase through the browser, I would like an option in the CLI to pass the token output of running `firebase login:ci` so that FlutterFire can use that token as an input when running firebase commands.

For example: The CLI runs `firebase projects:list --json` initially. This option would modify that command to `firebase projects:list --json --token="$FIREBASE_TOKEN"`.

### Reasoning

I think this feature would be useful for those trying to generate the `firebase_options.dart` file in a CI environment when the app ID is not known in advance. Example of this use case is building white labeled apps.

**Comment by exaby73** [comment]
Another, more common, use case could be where different projects are configured with different accounts. This allows the CLI to be ambiguous to the current logged in firebase account

**Comment by leo-neon** [comment]
@exaby73 May I ask, how did you manage to run flutterfire in Codemagic? I try to achieve the exact same thing for a white labeled app. 
In the post clone script I install (dart pub global activate) flutterfire and so on. In the pre-build script I try to run the command. 
It always says "Option ios-bundle-id is mandatory." I usually don't specify this when running the command locally since it fetches all arguments from my workspace directory. At the time of execution, Codemagic is in the workspace directory. I would love to find out more about your setup - any help would be very appreciated! 😊

**Comment by exaby73** [comment]
@leo-neon You can just pass `-i <bundle-id> -m <bundle-id>`. `-i` is for iOS, `-m` for MacOS. Don't worry, it won't register those platforms if you don't include them in `--platforms` :)

**Comment by leo-neon** [comment]
@exaby73 Thanks for your quick response 😊  I will give it a try in the next release cycle - hopefully it will save me some time when releasing 5 app updates at once 😆
