### ISSUE TITLE
request:  Add documentation how to use FlutterFire packages the old way without this tool

### ISSUE THREAD

**Issue by kinex** [invertase/flutterfire_cli#85]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Description

Please add documentation how to continue using FlutterFire without this tool i.e. the old way. There are several unclear items like do I need to put something to .gradle files in this case.

### Reasoning

I don't want to use this tool in my project. There were not any issues in the old way of downloading manually the required config files from Firebase and updating the files when needed (which is very rarely actually). This tool only adds complexity to my project and I will consider it also as a security risk.

Detected problems:
- The new generated files `firebase_options.dart` and `firebase_app_id_file.json` are not useful at least in Android / iOS projects. The same information is already available in the files `google-services.json` (Android) and `GoogleService-Info.plist` (iOS) which you cannot remove anyway, because at least Crashlytics and the plugin `google_sign_in` require them. I would bet at least 95% of the Flutter/Firebase apps use both Crashlytics and the plugin `google_sign_in`.

- Flavors are not supported and maintaining existing flavor implementation gets even more complex (due to the new required file `firebase_app_id_file.json` in the fixed location).

- It is much more clear and easier to maintain the project if the required information is in one place / platfrom i.e. `google-services.json` (Android) and `GoogleService-Info.plist` (iOS) and the application is initialized with `await Firebase.initializeApp()` without any parameters.

- The tool seems to create applications to Firebase without even confirming it from the user. This already happened to me when I tried the tool for the first time (the tool did not recognize the correct package id / bundle id from my project so it decided to add new applications to Firebase without any questions). Luckily it was only my Development project in Firebase. I don't want this kind of tool connecting to my production project in Firebase, not even with read access. That's why I say this tool is currently a security risk as the tool can even modify my Firebase projects. It is also unclear what it exactly does and when, and all this can be changed at any time when you update the tool. 

### Additional context and comments

Maybe the tool is useful for new developers trying Flutter/Firebase and to get started quickly, but for real-world production apps the tool it is currently only a new problem and a security risk.

I could consider using this tool again if you: 
- Totally remove need for  `google-services.json` and `GoogleService-Info.plist`, but I am not sure if it is technically possible.
- Allow using the tool in read-only mode (quaranteed that it does not modify any Firebase projects), or even offline.

**Comment by KKamishima** [comment]
Just sharing our experience.

> Totally remove need for `google-services.json` and `GoogleService-Info.plist`, but I am not sure if it is technically possible.

In our case, Android build failed to run without `google-services.json`. The app saw a fatal error at `onResume()` handler, where I suppose some Analytics data collection mechanics is present, by saying (native) Firebase SDK has not been initialized. Usually such initialization is automatically performed in `FirebaseInitProvider` using the default parameter values derived from `google-services.json` (in fact, Firebase Gradle plug-in converts it into a bundle of string resources and embed it into the app.)

To avoid such error without the presence of `google-services.json`, we need to explicitly initialize native Firebase SDK using parameter values defined in `firebase_options.dart` at an earlier stage of the execution of the app, way before Dart `main()` is executed. Although I have not tried it by myself, it would be theoretically possible by implementing `onCreate()` handler in `MainActivity` to initiate such explicit initialization. It involves execution of Dart code from inside the native part of the app, though.

In my opinion,  generating `firebase_options.dart` was a failed experiment and shall be obsoleted because:

1. The native Firebase SDKs for both iOS / Android suggest the automatic initialization based on  `google-services.json` and `GoogleService-Info.plist` is the primary way to go.
   - https://firebase.google.com/docs/android/setup
   - https://firebase.google.com/docs/ios/setup
2. Each set of these initialization parameters is inherently platform-dependent, there would be little reasoning on keeping it in platform-independent Dart code.

**Comment by kinex** [comment]
> 
> In my opinion, generating `firebase_options.dart` was a failed experiment and shall be obsoleted because:
> 
Exactly. Failed experiment and pretty much waste of time. I am 99% sure Crashlytics (same for Analytics?) must be initialized much earlier before any Dart code is executed and this alone is a showstopper issue for even considering to implement this kind of tool. Using `google-services.json` and `GoogleService-Info.plist` works great and what's most important allows keeping important things under the developer's control without all the risks this tool is causing to your Firebase project.

**Comment by russellwheatley** [comment]
Activate the latest FF CLI using `dart pub global activate flutterfire_cli `. The service files are now written for android & iOS. We're thinking of removing the Dart init code for android and iOS to clear up the confusion. If you want docs for manual steps, they're [archived here](https://firebase.flutter.dev/docs/manual-installation)
